(function () {
  function storyText(sentences) {
    return sentences.join(" ");
  }

  const storylines = Object.freeze({
    cinematicCaptainNova: {
      id: "cinematicCaptainNova",
      title: "Captain Nova's Rocket Mission",
      introductionArtwork: {
        src: "./assets/captain-nova-launch-bay-portal.png",
        alt: "Captain Nova standing in Mission Control beside the unfinished rocket while a glowing route opens toward deep space and Luma-7.",
      },
      endingArtwork: {
        src: "./assets/luma7-final-flight-wide.png",
        mobileSrc: "./assets/luma7-final-flight.png",
        desktopSrc: "./assets/luma7-final-flight-wide.png",
        alt: "Captain Nova standing on Luma-7 beside the landed rocket under a ringed planet, lightning, and green auroras.",
      },
      introduction: {
        kicker: "Introduction",
        pill: "Before Mission 1",
        secondaryPill: "8 Rocket Parts to Unlock",
        text: [
          "Welcome, Explorer. **Tonight, Mission Control has a real emergency in the stars.**",
          "A mysterious beacon has started flashing from deep space - far beyond Earth, past the Moon, past the comet trails, beyond even the maps in the station archives. Captain Nova has traced the signal to a hidden planet called Luma-7, a world wrapped in silver storms, glowing rings, and skies no human has ever seen. But the path to reach it is unstable. It opens only once, like a secret tunnel through space, and it is already beginning to flicker.",
          "There is only one ship fast enough to answer the call. **There is just one problem: the rocket is not finished.**",
          "Across the station, eight sealed chambers protect the missing rocket parts. Each chamber contains a challenge, a vital system, and another piece of the route to Luma-7. Solve the mission in each chamber, unlock the next rocket part, and help Captain Nova rebuild the ship before the skyway closes.",
          "If you can wake the rocket piece by piece, Captain Nova may become the first explorer ever to reach Luma-7. **Move fast. Think clearly. Stay brave.**",
        ],
      },
      missions: [
        {
          section: "Verbal",
          number: 1,
          title: "Verbal Challenge",
          rocketPart: "Rocket Base",
          completionArtwork: {
            src: "./assets/mission-1-rocket-base-unlocked.png",
            alt: "Mission 1 complete scene showing Captain Nova celebrating as the Rocket Base unlocks and rises into place.",
          },
          introduction: storyText([
            "Captain Nova rushes into the Word Vault, where glowing letters zip through the air like tiny comets and words crash together in bright loops of color.",
            "Beneath the storm, the **Rocket Base** lies sealed under a crystal floor of coded phrases.",
            "Mission Control reports that **the first coordinates to Luma-7 are hidden here**, but they will only appear when the right words are chosen and the language lock breaks.",
            "Every smart answer steadies the chamber, clears the meaning, and reveals more of the buried foundation.",
            "**Free the Rocket Base, Explorer,** and give the mission something strong enough to stand on.",
          ]),
          midMissionUpdate: storyText([
            "Mission Update.",
            "**The Word Vault is growing unstable.**",
            "Streams of letters are smashing together, syllables are snapping apart, and the sentence that anchors the Rocket Base is starting to dissolve into nonsense.",
            "If the chamber loses its meaning completely, the base could sink beneath the station floor again, along with **the first line of coordinates to Luma-7.**",
            "Captain Nova is bracing the vault doors while a cyclone of punctuation spins across the room.",
            "Mission Control says the chamber can still be saved, but only if **the strongest meaning is restored** before the whole vault locks itself shut.",
          ]),
          rewardDebrief: storyText([
            "**Victory.**",
            "The final word clicks into place, and the chamber gives a bright shimmering hum.",
            "The storm of letters spirals upward and snaps into a glowing sentence across the ceiling.",
            "Beneath Captain Nova's boots, the crystal floor cracks open in a ring of blue light.",
            "Slowly, powerfully, **the Rocket Base rises from below**, solid metal gleaming under the vault lights.",
            "Mission Control captures the first clear coordinates to Luma-7 and beams them to Captain Nova's console.",
            "With a grin, Captain Nova locks the base onto the launch frame.",
            "The ship is no longer just a plan.",
            "**Now it has a foundation.**",
          ]),
        },
        {
          section: "Math",
          number: 2,
          title: "Math Challenge",
          rocketPart: "Rocket Body",
          completionArtwork: {
            src: "./assets/mission-2-rocket-body-unlocked.png",
            alt: "Mission 2 complete scene showing Captain Nova as the Rocket Body lowers into place over the base.",
          },
          introduction: storyText([
            "Captain Nova steps into the Number Chamber, where giant glowing rings of numbers spin through the air like the gears of a cosmic machine.",
            "At the center floats the **Rocket Body**, trapped inside a buzzing field of shifting math energy.",
            "Mission Control explains that **the next coordinates to Luma-7** will only lock into place once the number rings are balanced and the chamber's patterns are solved.",
            "Every correct calculation weakens the field and steadies the spinning paths.",
            "Bright numbers crackle past Captain Nova like fireworks as the chamber hums louder.",
            "Solve carefully, Explorer, and **bring the Rocket Body down to meet the base.**",
          ]),
          midMissionUpdate: storyText([
            "Mission Update.",
            "**The Number Chamber is speeding up again.**",
            "The glowing rings are spinning faster, symbols are flashing across the walls, and the field around the Rocket Body is crackling brighter with every second.",
            "If the sequence overloads, the body could drift out of alignment and the rocket would lose **the frame it needs to follow the path toward Luma-7.**",
            "Captain Nova is trying to recalibrate the stabilizers, but the chamber only responds to correct calculations.",
            "A wrong move now could send the whole system into chaos.",
            "Stay calm, Explorer.",
            "**Balance the number storm before the field tears loose.**",
          ]),
          rewardDebrief: storyText([
            "**Success.**",
            "Your answers settle the number storm one ring at a time.",
            "First the outer ring slows, then the next, until all the glowing circles shine in perfect balance.",
            "With a deep metallic thunder, **the math field collapses in a flash.**",
            "The Rocket Body lowers into place and locks onto the base with a sharp, powerful clang.",
            "Mission Control cheers as the second line of the route to Luma-7 appears across the main screen.",
            "Captain Nova runs a fast systems scan, circles the growing ship, and gives an approving nod.",
            "The rocket is no longer just standing.",
            "**Now it has shape, strength, and a body built for the journey ahead.**",
          ]),
        },
        {
          section: "Nonverbal",
          number: 3,
          title: "Pattern Vision",
          rocketPart: "Rocket Window",
          completionArtwork: {
            src: "./assets/mission-3-rocket-window-unlocked.png",
            alt: "Mission 3 complete scene showing Captain Nova in the Hall of Patterns as the Rocket Window and hidden star route come into view.",
          },
          introduction: storyText([
            "Captain Nova enters the silent Hall of Patterns, where glowing shapes drift across the walls like pieces of a living star map.",
            "Triangles slide, circles turn, and lines blink in and out of view.",
            "No words appear here, and no numbers will help.",
            "Behind the shifting designs rests the **Rocket Window**, the lens that will let Captain Nova see the route once the ship leaves Earth behind.",
            "Mission Control believes **the beacon from Luma-7 is echoing through these hidden shapes**, but only an explorer who can spot the true design can reveal it.",
            "Study the clues carefully, **unlock the Window, and bring the distant path into view.**",
          ]),
          midMissionUpdate: storyText([
            "Mission Update.",
            "**The Hall of Patterns is shifting faster now.**",
            "Shapes are sliding out of place, bright symbols are fading at the edges, and the map hidden in the walls is starting to vanish into shadow.",
            "If the pattern breaks completely, the Rocket Window could stay sealed away and Captain Nova would have to **fly blind into deep space.**",
            "Mission Control says the signal from Luma-7 is still buried inside the moving light, but it is becoming harder to track every second.",
            "Captain Nova is holding position in the center of the chamber while shapes sweep around like silent birds.",
            "**Catch the true design, Explorer, before it disappears.**",
          ]),
          rewardDebrief: storyText([
            "**Brilliant work.**",
            "At the final moment, the hidden pattern snaps into perfect alignment.",
            "The wall glides open without a sound, and the **Rocket Window floats forward in a wash of silver light**, clear as crystal and bright enough to reflect a whole field of stars.",
            "Captain Nova carefully installs it into the growing ship.",
            "At once, the darkness beyond the station blooms with glowing route lines stretching toward Luma-7.",
            "Far ahead, a pale storm ring flickers in the distance like a secret doorway in space.",
            "For the first time, **the mission can truly see where it is going**, and Mission Control marks danger waiting farther ahead.",
          ]),
        },
        {
          section: "Spatial",
          number: 4,
          title: "Spatial Assembly",
          rocketPart: "Rocket Wings",
          completionArtwork: {
            src: "./assets/mission-4-rocket-wings-unlocked.png",
            alt: "Mission 4 complete scene showing Captain Nova as the Rocket Wings unfold into place in the Assembly Bay.",
          },
          introduction: storyText([
            "Captain Nova enters the Assembly Bay, where metal pieces drift in slow circles through a chamber full of humming magnetic light.",
            "Some parts are curved, some are sharp, and some only make sense when turned in exactly the right direction.",
            "Hidden inside this floating puzzle are the **Rocket Wings**, the steering fins needed to guide the ship through the debris field blocking the way to Luma-7.",
            "Mission Control can already see **rock, ice, and broken satellite metal** moving beyond the station like a river of spinning obstacles.",
            "Fit the pieces together in your mind, Explorer, and **let the wings unfold before the path closes.**",
          ]),
          midMissionUpdate: storyText([
            "Mission Update.",
            "**The Assembly Bay has turned into a metal storm.**",
            "Loose parts are spinning faster, magnets are snapping unpredictably, and the shape of the Rocket Wings is starting to break apart before it can lock together.",
            "If the pieces scatter too far, Captain Nova will never be able to steer safely through **the debris river between Earth and Luma-7.**",
            "Mission Control is trying to steady the magnetic field, but the chamber only responds to correct spatial choices.",
            "Captain Nova is dodging spinning parts and trying not to get smacked by a flying fin segment.",
            "**Think fast, Explorer, and rebuild the wings before the storm wins.**",
          ]),
          rewardDebrief: storyText([
            "**Excellent.**",
            "Just before the metal storm can rip the chamber apart, the final pieces align with a sharp metallic snap.",
            "The **Rocket Wings unfold from the air itself**, sleek and bright, then sweep into position on both sides of the ship.",
            "Captain Nova secures each wing and watches the control panel light up as the steering systems come alive.",
            "Mission Control confirms that the rocket can now survive the debris field ahead and stay on course for the beacon of Luma-7.",
            "The ship is no longer only strong.",
            "**Now it can turn, glide, and fight its way through danger** on the path to the hidden planet.",
          ]),
        },
        {
          section: "Patterns",
          number: 5,
          title: "Pattern Reactor",
          rocketPart: "Rocket Engine",
          completionArtwork: {
            src: "./assets/mission-5-rocket-engine-unlocked.png",
            alt: "Mission 5 complete scene showing Captain Nova as the Rocket Engine ignites with bright energy in the Reactor Core.",
          },
          introduction: storyText([
            "Captain Nova descends into the Reactor Core, where deep mechanical light pulses through the chamber in repeating streams of symbols.",
            "At the center waits the **Rocket Engine**, silent for now, because one missing symbol has broken the code that wakes its power.",
            "Without the engine, **the ship will never have the strength to cross the long dark stretch** between Earth and Luma-7.",
            "Mission Control can hear the core trying to start, then sputtering and falling silent each time the pattern slips apart.",
            "Study the sequence, Explorer.",
            "Find the missing piece, restore the rhythm, and **wake the engine before the chamber goes cold.**",
          ]),
          midMissionUpdate: storyText([
            "Mission Update.",
            "**The Reactor Core is flashing red from floor to ceiling.**",
            "Warning lights are pulsing out of rhythm, the symbol streams are breaking apart, and the engine heart is surging in short, uneven bursts.",
            "If the missing code is not restored soon, the chamber could shut down completely and the mission to Luma-7 would **end before the rocket even leaves the station.**",
            "Captain Nova is rerouting backup power, but the core will only answer to the true pattern.",
            "Sparks are jumping across the console, and the air in the chamber shakes with half-started engine pulses.",
            "**Restore the sequence, Explorer, before the last light goes dark.**",
          ]),
          rewardDebrief: storyText([
            "**Outstanding.**",
            "The missing symbol slides into place, and for one breathless second the Reactor Core goes completely silent.",
            "Then the chamber erupts in brilliant gold light as **the Rocket Engine roars awake** beneath the ship.",
            "The alarms stop.",
            "The floor steadies.",
            "A deep rolling hum passes through the station like distant thunder.",
            "Mission Control reports that power levels are rising exactly as planned, strong enough to carry Captain Nova out beyond Earth and toward Luma-7.",
            "Captain Nova grips the control rail and smiles as the engine glow floods the room.",
            "**Now the rocket has real power**, and the mission can finally chase the beacon into deep space.",
          ]),
        },
        {
          section: "Analogies",
          number: 6,
          title: "Analogy Link",
          rocketPart: "Astronaut Seat",
          completionArtwork: {
            src: "./assets/mission-6-astronaut-seat-unlocked.png",
            alt: "Mission 6 complete scene showing Captain Nova as the Astronaut Seat rises into the Command Chamber and links to the cockpit.",
          },
          introduction: storyText([
            "Captain Nova enters the Command Chamber, where the next lock is hidden inside chains of connected ideas glowing across the main screen.",
            "Pairs of clues appear, linked by a relationship that must be understood before the system will open.",
            "Behind the control wall waits the **Astronaut Seat**, the cockpit link that will let Captain Nova command the rocket once the engines ignite.",
            "Mission Control warns that without this link, **even a fully powered ship could drift off course** before reaching Luma-7.",
            "Read each connection carefully, Explorer.",
            "Find the matching idea, restore the bridge between thought and control, and **wake the pilot's place at the heart of the ship.**",
          ]),
          midMissionUpdate: storyText([
            "Mission Update.",
            "**The Command Chamber is reacting badly to broken links.**",
            "The main screen is flickering, clue chains are splitting apart, and the control wall is starting to seal the Astronaut Seat behind layers of dark glass.",
            "If the idea network collapses, Captain Nova could **lose direct control of the rocket** before launch even begins.",
            "Mission Control can keep the chamber alive a little longer, but only a correct connection will restore the system.",
            "Captain Nova is moving from screen to screen as sparks of green light zip through the command lines.",
            "**Follow the relationships carefully, Explorer, and reconnect the chain before the control system shuts you out.**",
          ]),
          rewardDebrief: storyText([
            "**Brilliant thinking.**",
            "When the final connection becomes clear, the broken clue chains flare bright green and race across the screens in one complete circuit.",
            "The sealed wall slides open, and a hidden platform rises from the floor carrying the **Astronaut Seat** into the light.",
            "Captain Nova installs it inside the cockpit, and the ship answers immediately.",
            "Displays awaken, steering lines sync, and route markers settle firmly on the console.",
            "**For the first time, every major system is listening to the pilot.**",
            "The rocket feels less like a pile of unlocked parts and more like a true ship, ready to obey Captain Nova on the long journey toward Luma-7.",
          ]),
        },
        {
          section: "Categories",
          number: 7,
          title: "Sorting Protocol",
          rocketPart: "Launch Flames",
          completionArtwork: {
            src: "./assets/mission-8-launch-glow-unlocked.png",
            alt: "Mission 7 complete scene showing Captain Nova as the Launch Flames ignite beneath the rocket and the countdown wakes.",
          },
          introduction: storyText([
            "Captain Nova enters the Launch Grid, where glowing objects drift through the air in crossing streams of light.",
            "Some belong together, some do not, and the ignition system will stay locked until the right groups are sorted into perfect order.",
            "This chamber controls the **Launch Flames**, the roaring fire the rocket needs to break free of Earth and begin the chase to Luma-7.",
            "Mission Control can already feel **the countdown trying to wake** beneath the platform.",
            "Choose carefully, Explorer.",
            "Clear the confusion from the grid, sort every object into the right stream, and **bring the ignition channels into formation before the launch window slips away.**",
          ]),
          midMissionUpdate: storyText([
            "Mission Update.",
            "**The Launch Grid is starting to jam.**",
            "Objects are crossing into the wrong streams, bright lanes are clogging with bad matches, and the ignition channels are flickering instead of opening cleanly.",
            "If the sorting network locks up, the Launch Flames may fail to ignite and the rocket could lose **its only chance to leave Earth before the path to Luma-7 closes.**",
            "Captain Nova is holding the countdown at the edge of zero while Mission Control vents excess heat from the platform below.",
            "The chamber is glowing hotter every second.",
            "**Sort with care, Explorer, and clear the grid before the launch sequence dies completely.**",
          ]),
          rewardDebrief: storyText([
            "**Amazing work.**",
            "Just before the grid can freeze, the final groups slide into their correct streams and the entire chamber flashes white.",
            "A heartbeat later, powerful **Launch Flames burst to life beneath the rocket** in waves of gold, blue, and silver fire.",
            "The platform trembles.",
            "The countdown wakes.",
            "Captain Nova looks through the cockpit glass and sees the path to Luma-7 burning bright on the horizon.",
            "Mission Control confirms that liftoff is now possible.",
            "**Only one final system stands between the mission and the stars.**",
            "Deep in the station, the Final Control Room is already waking and waiting for the last logic chain to be solved.",
          ]),
        },
        {
          section: "Logic",
          number: 8,
          title: "Final Logic System",
          rocketPart: "Launch Glow",
          completionArtwork: {
            src: "./assets/mission-8-launch-glow-unlocked-v2.png",
            alt: "Mission 8 complete scene showing Captain Nova as the final launch system surges awake and the rocket glows with full power.",
          },
          introduction: storyText([
            "Captain Nova enters the Final Control Room, where the last challenge protects the launch sequence itself.",
            "Across the main console stretches a chain of clues, and each one must be understood in the right order before the rocket will accept the command to fly.",
            "This system controls the **Launch Glow**, the final surge that links every unlocked part into one living machine.",
            "Mission Control can see **the skyway to Luma-7 opening** beyond the station now, bright, narrow, and already fading at the edges.",
            "Stay calm, Explorer.",
            "Solve the final logic chain, bring the whole rocket to life, and **launch before the window closes for good.**",
          ]),
          midMissionUpdate: storyText([
            "Mission Update.",
            "**The Final Control Room is running out of time.**",
            "Lights are blinking on and off across the console, the launch sequence keeps stalling in mid-countdown, and the skyway to Luma-7 is narrowing with every passing second.",
            "If the final clues are not solved now, the rocket could power down with **every part assembled but no way to fly.**",
            "Captain Nova is strapped into the cockpit, gloved hands hovering over the controls, while Mission Control watches the last safe opening flicker against the stars.",
            "**This is the final test, Explorer.**",
            "Hold the logic chain together and awaken the launch before the path disappears into darkness.",
          ]),
          rewardDebrief: storyText([
            "**Mission complete.**",
            "The final clue locks into place, and the entire control system surges awake in a single blaze of light.",
            "A brilliant **Launch Glow races across the rocket** from base to nose, stitching every unlocked part into one shining machine ready for flight.",
            "The engine hum deepens.",
            "The cockpit steadies.",
            "The console turns green across every screen.",
            "Captain Nova grips the controls as the route to Luma-7 burns clear beyond the stars.",
            "**Mission Control confirms it: all systems are go.**",
            "The ship is ready.",
            "The countdown is alive.",
            "And because you held the final chain together, the great journey can finally begin.",
          ]),
        },
      ],
      endings: [
        {
          id: "ending_95_plus",
          label: "Excellent",
          minScore: 95,
          maxScore: 100,
          text: [
            "With every chamber solved, Captain Nova seals the hatch, settles into the Astronaut Seat, and begins the final countdown. The Rocket Base grips the launch pad, the Window shines with the path you uncovered, the Wings lock into perfect position, the Engine roars awake, the Launch Flames surge beneath the platform, and the Launch Glow washes the hull in bright silver light.",
            "**At zero, the rocket launches.** It blasts upward through clouds of steam and roaring fire, shaking the station as it tears into the night sky. Earth falls away. The Moon flashes past. Stars open in every direction.",
            "Captain Nova follows the route you restored, flying through a river of tumbling debris, banking between spinning rocks and broken ice, then bursting through a glowing comet gate that lights the whole ship blue-white. Every part works beautifully. Every system responds instantly. The rocket flies like it was always meant to reach the impossible.",
            "**And then, through the silver storm ahead, Luma-7 appears.**",
            "It is more incredible than anyone imagined: blue oceans glowing beneath crystal clouds, giant glassy storm rings circling the planet, green auroras pouring through the sky, and valleys sparkling like they are filled with stars. Captain Nova guides the ship through the shining atmosphere, dodges a crown of silver lightning, and lands in a wide glowing plain at the foot of a crystal mountain range.",
            "Mission Control erupts in cheers loud enough to rattle the speakers. Captain Nova sends the first clear hello from Luma-7 back to Earth, followed by images of its skies, its rings, and its mysterious glowing land.",
            "Because of your brilliant work, the beacon was answered. The hidden planet was reached. Captain Nova becomes the first explorer to stand on Luma-7, and this mission is remembered forever as one of the greatest adventures in space history.",
          ],
        },
        {
          id: "ending_85_94",
          label: "Great Job",
          minScore: 85,
          maxScore: 94,
          text: [
            "The countdown reaches zero, and Captain Nova launches into the night with a rocket that feels strong, fast, and almost perfect. The ship rises in a roar of light, breaks through the clouds, and races away from Earth toward the narrow skyway leading to Luma-7.",
            "The Window glows with the route you helped uncover. The Engine hums with steady power. The Wings guide the ship through drifting debris and shimmering comet dust as Captain Nova flies deeper into space. The beacon ahead grows brighter and brighter until, at last, the hidden planet comes into view.",
            "**Luma-7.**",
            "A shimmering world wrapped in silver weather, swirling rings, and glowing rivers of light. Captain Nova reaches orbit and circles the planet, sending back breathtaking images of shining seas, bright storm crowns, enormous mountain shadows, and flashes of green aurora racing across the sky. Mission Control can barely believe what it is seeing.",
            "But a few systems are not tuned quite well enough for a safe landing. The ship can orbit. It can scan. It can get close. But the descent would be too risky.",
            "**So Mission Control gives the order to turn back.**",
            "Even so, the mission is a triumph. The beacon was reached. The hidden planet was revealed. Captain Nova returns to Earth carrying maps, data, and images that will guide the next launch even farther into the unknown. The first landing will have to wait - but because of you, the path is open.",
          ],
        },
        {
          id: "ending_75_84",
          label: "Nice Work",
          minScore: 75,
          maxScore: 84,
          text: [
            "Captain Nova launches with courage and a rocket that climbs cleanly into the dark, carrying the dream of Luma-7 high above Earth. The ship clears the atmosphere, speeds past the Moon, and follows the route you rebuilt through drifting fields of ice, dust, and silent starlight.",
            "**For a while, everything feels possible.**",
            "The beacon ahead grows stronger. The Window stays bright. Captain Nova even catches a first real glimpse of Luma-7 at the far edge of space - glowing through silver storms like a lantern hidden behind clouds. Mission Control receives distant scans and blurry but thrilling images of the planet's ringed skies.",
            "But as the journey continues, a few systems begin to strain. Power wobbles. Guidance needs extra correction. The ship can still fly, but not with the steady strength needed to cross the final distance safely and begin an approach.",
            "**Mission Control makes the hard call to turn back before the mission slips into danger.**",
            "Captain Nova returns to Earth with real spaceflight experience, a clearer map, fresh readings of the beacon, and the unforgettable thrill of having seen the hidden world with their own eyes.",
            "The mission falls short of orbit or landing, but it proves something important: **Luma-7 is real. The route works. And the next rocket could go all the way.**",
          ],
        },
        {
          id: "ending_60_74",
          label: "Good Effort",
          minScore: 60,
          maxScore: 74,
          text: [
            "The rocket launches with a fierce shake, and Captain Nova guides it upward as alarms flicker and the station falls away below. The ship breaks through the clouds and reaches space, where Earth glows blue beneath the Window and the stars stretch wide in every direction.",
            "**Far ahead in the darkness, the beacon of Luma-7 glimmers like a promise.**",
            "For one shining stretch of the journey, it feels like the mission might make it. The ship follows the early part of the route, crosses into near-Earth space, and captures valuable readings from the skyway. Captain Nova keeps the rocket steady with skill and focus while Mission Control tracks the flickering signal ahead.",
            "But the voyage cannot hold together for long. Some systems struggle to work together. Power rises and falls unevenly. Guidance needs more correction than the rocket can handle. The ship does not have the strength or stability it needs to chase Luma-7 safely across deep space.",
            "**Mission Control orders an early return.**",
            "Captain Nova brings the ship home with calm hands and strong flying, and the mission still earns an important victory: the rocket flew, the beacon was seen, data was collected, and the path ahead became clearer than ever before.",
            "This was not the great crossing to Luma-7 - not yet - but it was a brave step toward it, and the next build will be better prepared.",
          ],
        },
        {
          id: "ending_below_60",
          label: "Keep Trying",
          minScore: 0,
          maxScore: 59,
          text: [
            "Captain Nova begins the countdown, and for one breathless moment the whole station seems to hold still.",
            "The Engine surges. The Launch Flames burst unevenly beneath the rocket. The glowing route to Luma-7 shines across the Window like a dream almost close enough to touch. Slowly, the ship rises from the pad in a roar of heat and light.",
            "**But the rocket is not ready.**",
            "Warning lights flood the cockpit. Key systems pull against one another. The climb becomes shaky, then unstable. Captain Nova fights to steady the controls as Mission Control watches the numbers swing in the wrong direction.",
            "**The rocket rises only a short distance before the order comes: abort and return.**",
            "With calm focus and careful skill, Captain Nova guides the ship safely back to the launch pad while the last of the skyway fades above the station. The beacon still flashes somewhere far beyond the darkness, unanswered for now. No one reaches Luma-7 today.",
            "But the mission is not wasted. Every chamber you cleared revealed more of what the rocket needs. Every answer brought Captain Nova one step closer to the stars. Every attempt helped build the path forward.",
            "The hidden planet is still waiting out there beyond the storm rings and the dark, and with stronger problem-solving on the next run, this unfinished launch could one day become a triumphant journey all the way to Luma-7.",
          ],
        },
      ],
    },
  });

  // Change this id to swap to another storyline pack without touching app logic.
  const activeStorylineId = "cinematicCaptainNova";
  const activeStoryline = storylines[activeStorylineId] || Object.values(storylines)[0];

  const content = {
    hero: {
      eyebrow: "Mission Control",
      title: "Captain Nova's Rocket Mission",
      copy: "A story-driven gifted practice adventure for brave young engineers.",
      metrics: {
        steps: "{count} Mission Steps",
        parts: "{count} Rocket Parts",
        time: "Final Launch in {minutes} Minutes",
      },
    },
    scoreboard: {
      kicker: "Explorer Record",
      awaitingName: "Type an explorer name",
      awaitingScore: "Enter the explorer name below to show only that explorer's best score.",
      loading: "Checking this explorer's saved record.",
      empty: "No saved record yet for this explorer.",
      localSaveSuccess: "Explorer record saved on this device.",
      deviceOnlyWarning: "Explorer record saved on this device. Online sync could not update just now.",
      deviceResetSuccess: "Every saved explorer record on this device has been cleared.",
      allResetSuccess: "Every saved explorer record has been cleared.",
      resetPrompt: "Enter the admin PIN to clear saved explorer records.",
      resetConfirm: "Clear every saved explorer record on this device? This cannot be undone.",
    },
    parentArea: {
      toggle: "Parent Area",
      kicker: "Parent Area",
      copy: "Restart the mission or manage saved scores without interrupting the story.",
      storyOnlyLabel: "Story Only",
      storyOnlyHelp: "Skip the questions and play only the mission story scenes.",
      restart: "Restart Mission",
      reset: "Reset Saved Scores",
    },
    dashboard: {
      buildTitle: "Rocket Build",
      timerLabel: "Mission Timer",
      scoreLabel: "Mission Score",
      buildNote: "Each solved mission step helps Captain Nova finish the rocket.",
      missionsTitle: "Rocket Missions",
      tipTitle: "Captain Nova Tip",
      tipCopy:
        "Take a slow breath, read carefully, and imagine each smart answer clicking a new rocket part into place.",
    },
    start: {
      briefingTitle: "Mission Briefing",
      nameLabel: "Explorer Name",
      namePlaceholder: "Type your explorer name here",
      emptyNameHint: "Mission Control needs your name before the countdown can begin.",
      readyNameHint: "Press Enter to start Mission 1: Verbal Challenge.",
      readyStoryOnlyNameHint: "Press Enter to begin Story Only mode.",
      emptyPrompt: "Type your name to join Captain Nova's mission.",
      readyPrompt: "Hi {name}! Captain Nova is ready for liftoff.",
      counter: "{count} mission steps across {missions} missions",
      badge: "Mission Briefing",
      emptyNextHint: "Type your name to begin the mission.",
      readyNextHint: "Press Enter to start Mission 1: Verbal Challenge.",
      readyStoryOnlyNextHint: "Press Enter to play the story route.",
      playerReadyNote: "Explorer {name}, your mission console is ready.",
    },
    question: {
      counter: "Mission Step {current} of {total}",
      selectHint: "Choose an answer to power up Check Answer.",
      validateHint: "Press Check Answer to power the next rocket step.",
      allAnsweredHint: "All {count} mission steps are complete. Launch the rocket when you are ready.",
      autoAdvanceHint: "Rocket step locked in. Loading the next mission step...",
      lockedHint: "Rocket step locked in. Press Next Mission Step.",
      nextMissionHint: "Rocket part secured. Press Next mission.",
      storyOnlyPrompt: "Story Only mode is on. Follow Captain Nova through each mission scene.",
      storyOnlyHint: "Use the modal button to continue the story.",
      playerNote: "Explorer {name} is flying Mission {missionNumber}.",
      buttons: {
        check: "Check Answer",
        next: "Next Mission Step",
        nextMission: "Next mission",
        launch: "Launch the Rocket",
        finished: "Mission Complete",
        storyOnly: "Story Only Active",
      },
      feedback: {
        correctTitle: "Rocket power confirmed",
        wrongTitle: "Mission Control correction",
        yourAnswer: "Your answer:",
        correctAnswer: "Correct answer:",
        why: "Why:",
        noAnswer: "No answer selected",
      },
    },
    results: {
      eyebrow: "Launch Report",
      summarySuffix: "Captain Nova's launch report is ready below.",
      timeSummary: "Mission time used: {used} of {total}.",
      storyOnlyHeadline: "{name} completed Captain Nova's full story route.",
      storyOnlySummary: "Story Only mode played every mission scene without quiz questions.",
      storyOnlyTimeSummary: "Story Only mode keeps the focus on the adventure, so mission timing is turned off.",
      retry: "Build Another Rocket",
      back: "Return to Mission",
      debriefTitle: "Mission Debrief",
      debriefCopy: "Open this report to review missed mission steps and the correct solutions.",
      perfectTitle: "Legendary Launch",
      perfectBody: "Captain Nova's rocket launched with every system working perfectly.",
      sectionSummary: "{correct} mission steps powered out of {total}",
      sectionPercent: "{percent}% mission power in this system",
      summaryBands: [
        {
          min: 85,
          text: "Legendary engineering. Captain Nova built a rocket ready for deep space.",
        },
        {
          min: 70,
          text: "Strong mission work. A little more precision will send the next rocket even farther.",
        },
        {
          min: 55,
          text: "Good progress. A few more practice missions will make the rocket stronger and steadier.",
        },
        {
          min: 0,
          text: "This launch was a brave start. Review the mission debrief and build an even better rocket next time.",
        },
      ],
      endingTitle: "Captain Nova's Final Flight",
      scorePill: "{percent}% mission score",
      completePill: "Mission Complete",
    },
    activeStorylineId,
    storylines,
    story: activeStoryline,
    gamification: {
      messages: {
        correct: [
          "Rocket power rising!",
          "Mission Control says yes!",
          "Nice work, explorer!",
          "Captain Nova is impressed!",
        ],
        gentle: [
          "Almost there, explorer!",
          "Mission Control has a hint for you.",
          "Keep building, you are doing great!",
          "The next rocket step is waiting!",
        ],
        midpoint: [
          "Star boost unlocked!",
          "Halfway through this mission!",
          "Captain Nova found extra power!",
          "Your rocket just got brighter!",
        ],
        sectionComplete: [
          "Rocket part unlocked!",
          "Mission complete!",
          "Another rocket piece clicked into place!",
          "Captain Nova is ready for the next system!",
        ],
        final: [
          "Countdown complete!",
          "The rocket is ready to launch!",
          "Captain Nova can blast off now!",
          "Adventure complete!",
        ],
      },
      introductionTitle: "Mission Introduction",
      introductionBody: "Captain Nova has a new mission briefing for you.",
      introductionReward: "Unlock: {reward}",
      introductionButton: "Start mission",
      midpointTitle: "Mission Update",
      midpointBody: "The mission is halfway complete, and Captain Nova needs one more strong push.",
      midpointButton: "Continue mission",
      sectionCompleteTitle: "{reward} unlocked!",
      sectionCompleteBody: "Mission complete. Captain Nova just locked {reward} into place.",
      sectionCompleteButton: "Next mission",
      finalTitle: "All missions complete!",
      finalBody: "Every rocket system is in place. Captain Nova can begin the final countdown.",
      finalReward: "Rocket fully assembled",
      finalButton: "Finish mission",
    },
  };

  globalThis.CaptainNovaContent = Object.freeze(content);
})();
