(function () {
  function storyText(sentences) {
    return sentences.join(" ");
  }

  const storylines = Object.freeze({
    cinematicCaptainNova: {
      id: "cinematicCaptainNova",
      title: "Captain Nova's Rocket Mission",
      introduction: {
        kicker: "Introduction",
        pill: "Before Mission 1",
        secondaryPill: "8 Rocket Parts to Unlock",
        text: storyText([
          "Welcome, Explorer.",
          "Tonight, Mission Control has a real emergency in the stars.",
          "A mysterious beacon has started flashing from deep space - far beyond Earth, past the Moon, past the comet trails, beyond even the maps in the station archives.",
          "Captain Nova has traced the signal to a hidden planet called Luma-7, a world wrapped in silver storms, glowing rings, and skies no human has ever seen.",
          "But the path to reach it is unstable.",
          "It opens only once, like a secret tunnel through space, and it is already beginning to flicker.",
          "There is only one ship fast enough to answer the call.",
          "There is just one problem: the rocket is not finished.",
          "Across the station, eight sealed chambers protect the missing rocket parts.",
          "Each chamber contains a challenge, a vital system, and another piece of the route to Luma-7.",
          "Solve the mission in each chamber, unlock the next rocket part, and help Captain Nova rebuild the ship before the skyway closes.",
          "Move fast.",
          "Think clearly.",
          "Stay brave.",
          "If you can wake the rocket piece by piece, Captain Nova may become the first explorer ever to reach Luma-7.",
        ]),
      },
      missions: [
        {
          section: "Verbal",
          number: 1,
          title: "Verbal Challenge",
          rocketPart: "Rocket Base",
          introduction: storyText([
            "Captain Nova enters the Word Vault, where glowing letters drift through the dark like lanterns in zero gravity.",
            "Beneath the turning words sleeps the Rocket Base, sealed inside a floor of crystal code.",
            "Mission Control has learned that the first coordinates for Luma-7 are hidden in this chamber, but they will only appear when the right words are chosen and the language lock is broken.",
            "Each smart answer steadies the storm, sharpens the meaning, and reveals more of the buried foundation.",
            "Stay focused, Explorer.",
            "Free the Rocket Base here, and the mission will finally have something strong enough to stand on.",
          ]),
          midMissionUpdate: storyText([
            "Mission Update.",
            "The Word Vault is flaring.",
            "Streams of letters are colliding, words are tearing apart, and the phrase that anchors the Rocket Base is beginning to blur into nonsense.",
            "If the chamber loses its meaning completely, the base could sink back beneath the station floor and the first line of coordinates to Luma-7 could vanish with it.",
            "Captain Nova is holding the vault doors open against the pressure wave, but not for long.",
            "Trust the strongest meaning in each choice and restore order before the chamber seals itself again.",
          ]),
          rewardDebrief: storyText([
            "Victory.",
            "As the final word locks into place, the storm of letters sweeps upward and forms a bright sentence across the ceiling.",
            "The crystal floor opens, and the Rocket Base rises from below in a circle of blue light, solid enough to carry every part still to come.",
            "At the same moment, Mission Control captures the first clear line of coordinates to Luma-7 and beams them to Captain Nova's console.",
            "With a deep breath and a relieved smile, Captain Nova bolts the base into position.",
            "The ship is no longer only a plan - it has a foundation, and the adventure has truly begun.",
          ]),
        },
        {
          section: "Math",
          number: 2,
          title: "Math Challenge",
          rocketPart: "Rocket Body",
          introduction: storyText([
            "Captain Nova steps into the Number Chamber, where luminous rings of numbers rotate around a suspended core of metal and light.",
            "At the center floats the Rocket Body, trapped inside a field of shifting math energy that will not release its grip until the chamber's patterns are solved.",
            "Mission Control warns that the route from the Word Vault is incomplete without the body's navigation frame, because the next coordinates can only lock into place once the number rings are balanced.",
            "Every correct calculation weakens the field and steadies the spinning paths.",
            "Solve the chamber, Explorer, and the Rocket Body will descend to meet the base.",
          ]),
          midMissionUpdate: storyText([
            "Mission Update.",
            "The Number Chamber is accelerating again.",
            "The shining rings are spinning faster, the math field is crackling brighter, and the Rocket Body is starting to drift away from the capture beam.",
            "If the sequence overloads, the body could slide out of alignment and the ship would lose the frame needed to follow the path toward Luma-7.",
            "Captain Nova is recalibrating the stabilizers, but only your answers can bring the chamber back under control.",
            "Keep calculating carefully and bring the spinning patterns into balance before the field tears loose.",
          ]),
          rewardDebrief: storyText([
            "Success.",
            "Your answers calm the number storm, and one by one the glowing rings slow until they shine in perfect balance.",
            "With a thunderous clang, the math field collapses and the Rocket Body lowers into place, locking onto the base with sparks dancing along its seams.",
            "Mission Control cheers as the second line of the route to Luma-7 snaps into focus across the main screen.",
            "Captain Nova circles the ship, checks the alignment, and reports that the structure is strong, steady, and ready for the next system.",
            "The rocket now has a true shape.",
          ]),
        },
        {
          section: "Nonverbal",
          number: 3,
          title: "Pattern Vision",
          rocketPart: "Rocket Window",
          introduction: storyText([
            "Captain Nova moves into the Hall of Patterns, a silent chamber where glowing shapes glide across the walls like pieces of a living star map.",
            "No words appear here, and no numbers will help.",
            "Behind the shifting designs rests the Rocket Window, the clear lens that will let Captain Nova see the route ahead once the ship leaves Earth behind.",
            "Mission Control believes the beacon from Luma-7 echoes through these hidden patterns, but only an explorer who can spot the true design can reveal it.",
            "Study the clues carefully, unlock the Window, and bring the distant path into view.",
          ]),
          midMissionUpdate: storyText([
            "Mission Update.",
            "The Hall of Patterns is changing faster now.",
            "Shapes are sliding out of place, bright symbols are fading at the edges, and the map hidden in the walls is beginning to disappear into shadow.",
            "If the pattern breaks completely, the Rocket Window could stay sealed away and Captain Nova would have to fly blind into deep space.",
            "Mission Control can still detect the signal from Luma-7 beneath the shifting light, but only if you hold the right pattern in place.",
            "Look closely, stay calm, and catch the design before it vanishes.",
          ]),
          rewardDebrief: storyText([
            "Brilliant work.",
            "At the final moment, the hidden pattern snaps into perfect alignment and the wall glides open without a sound.",
            "The Rocket Window floats forward in a wash of silver light, clear as glass and bright enough to mirror a field of stars.",
            "When Captain Nova installs it into the growing ship, the dark beyond the station suddenly blooms with the next stretch of the route to Luma-7.",
            "Far ahead, a pale storm ring flickers in the distance.",
            "For the first time, the mission can truly see where it is going.",
            "Mission Control marks the debris river beyond the station and warns that the rocket will need strong wings to cross it safely.",
          ]),
        },
        {
          section: "Spatial",
          number: 4,
          title: "Spatial Assembly",
          rocketPart: "Rocket Wings",
          introduction: storyText([
            "Captain Nova enters the Assembly Bay, where metal pieces drift in slow circles through a chamber filled with humming magnetic light.",
            "Some parts are curved, some are sharp, and some only make sense when turned in exactly the right direction.",
            "Hidden inside this floating puzzle are the Rocket Wings, the steering fins needed to guide the ship through the shattered debris field that guards the way to Luma-7.",
            "Mission Control can already see the field building beyond the station, waiting like a maze of moving shadows.",
            "Fit the pieces together in your mind, solve the assembly, and let the wings unfold before the path closes.",
          ]),
          midMissionUpdate: storyText([
            "Mission Update.",
            "The Assembly Bay has erupted into a metal storm.",
            "Loose pieces are spinning faster, magnets are snapping unpredictably, and the shape of the Rocket Wings is starting to break apart before it can lock together.",
            "If the pieces scatter too far, Captain Nova will never be able to steer safely through the debris river between Earth and Luma-7.",
            "Mission Control is trying to steady the field, but the chamber only responds to correct spatial choices.",
            "Think fast, turn the pieces in your mind, and bring the wings together before the storm tears the puzzle apart.",
          ]),
          rewardDebrief: storyText([
            "Excellent.",
            "Just before the spinning storm can rip the chamber apart, the final pieces align with a sharp metallic snap.",
            "The Rocket Wings unfold from the air itself and sweep into position on both sides of the ship, sleek, bright, and perfectly balanced.",
            "Captain Nova secures each wing and watches the control panel glow as steering systems come alive across the cockpit.",
            "Mission Control confirms that the rocket can now survive the debris field ahead and keep chasing the signal from Luma-7.",
            "The ship is no longer only strong - it can now be guided through danger.",
          ]),
        },
        {
          section: "Patterns",
          number: 5,
          title: "Pattern Reactor",
          rocketPart: "Rocket Engine",
          introduction: storyText([
            "Captain Nova descends into the Reactor Core, where deep mechanical light pulses through the chamber in repeating streams of symbols.",
            "At the center waits the Rocket Engine, silent for now, because one missing symbol has broken the code that wakes its power.",
            "Without the engine, the ship will never have the strength to cross the long dark stretch between Earth and Luma-7.",
            "Mission Control can hear the core trying to start, then falling silent again as the pattern slips apart.",
            "Study the sequence, find the missing piece, and restore the rhythm before the chamber goes cold.",
          ]),
          midMissionUpdate: storyText([
            "Mission Update.",
            "The Reactor Core is flashing red from floor to ceiling.",
            "Warning lights are pulsing out of rhythm, the symbol streams are breaking apart, and the engine heart is surging in short, uneven bursts.",
            "If the missing code is not restored soon, the chamber could shut down completely and the mission to Luma-7 would end before the rocket ever leaves the station.",
            "Captain Nova is rerouting backup power, but the core will only answer to the true pattern.",
            "Stay sharp, Explorer, and restore the sequence before the last light goes dark.",
          ]),
          rewardDebrief: storyText([
            "Outstanding.",
            "The missing symbol slides into place, and for one breathless second the Reactor Core falls silent.",
            "Then the entire chamber floods with brilliant light as the Rocket Engine roars awake beneath the ship.",
            "The warning alarms stop, the floor steadies, and a deep golden hum rolls through the station like distant thunder.",
            "Mission Control reports that the power levels are rising exactly as planned, strong enough to carry Captain Nova across the void toward Luma-7.",
            "Now the rocket has the force to chase the beacon beyond Earth.",
          ]),
        },
        {
          section: "Analogies",
          number: 6,
          title: "Analogy Link",
          rocketPart: "Astronaut Seat",
          introduction: storyText([
            "Captain Nova reaches the Command Chamber, where the next lock is hidden inside chains of connected ideas that pulse across the main screen.",
            "Pairs of clues appear, linked by a relationship that must be understood before the system will open.",
            "Behind the control wall waits the Astronaut Seat, the final cockpit link that will let Captain Nova command the rocket once the engines ignite.",
            "Mission Control warns that without this link, even a fully powered ship could drift off course before reaching Luma-7.",
            "Read each connection carefully, find the matching idea, and restore the bridge between thought and control.",
          ]),
          midMissionUpdate: storyText([
            "Mission Update.",
            "The Command Chamber is reacting badly to broken links.",
            "The main screen is flickering, the clue chains are splitting apart, and the control wall is starting to seal the Astronaut Seat behind layers of dark glass.",
            "If the idea network collapses, Captain Nova could lose direct control of the rocket before the launch even begins.",
            "Mission Control can keep the chamber alive for a little longer, but only a correct connection will restore the system.",
            "Follow the relationships carefully and bring the command network back into harmony.",
          ]),
          rewardDebrief: storyText([
            "Brilliant thinking.",
            "When the final connection becomes clear, the broken clue chains flare bright green and race across the screen in one complete circuit.",
            "The sealed wall opens, and a hidden platform rises smoothly from the floor carrying the Astronaut Seat into the light.",
            "Captain Nova installs it inside the cockpit, and the ship answers immediately - displays awaken, steering lines sync, and the route to Luma-7 settles firmly on the console.",
            "For the first time, every major system is listening to the pilot.",
            "The rocket is beginning to feel alive.",
          ]),
        },
        {
          section: "Categories",
          number: 7,
          title: "Sorting Protocol",
          rocketPart: "Launch Flames",
          introduction: storyText([
            "Captain Nova enters the Launch Grid, where glowing objects drift through the air in crossing streams of light.",
            "Some belong together, some do not, and the entire ignition system will stay locked until the right groups are sorted into perfect order.",
            "This chamber controls the Launch Flames - the roaring fire the rocket needs to break free of Earth and begin the chase to Luma-7.",
            "Mission Control can already feel the countdown trying to wake beneath the platform.",
            "Choose carefully, clear the confusion from the grid, and bring the ignition channels into the right formation before the launch window slips away.",
          ]),
          midMissionUpdate: storyText([
            "Mission Update.",
            "The Launch Grid is starting to jam.",
            "Objects are crossing into the wrong streams, bright lanes are clogging with the wrong matches, and the ignition channels are flickering instead of opening cleanly.",
            "If the sorting network locks up, the Launch Flames may fail to ignite and the rocket could lose its only chance to leave Earth before the path to Luma-7 closes.",
            "Captain Nova is holding the countdown at the edge of zero while Mission Control vents excess heat from the platform.",
            "Sort with care and clear the grid before the launch sequence dies.",
          ]),
          rewardDebrief: storyText([
            "Amazing work.",
            "Just before the grid can freeze, the final groups slide into their correct streams and the entire chamber flashes white.",
            "A beat later, powerful Launch Flames burst to life beneath the rocket in waves of gold, blue, and silver fire.",
            "The platform trembles, the countdown wakes, and Captain Nova looks through the cockpit glass to see the path to Luma-7 burning bright on the horizon.",
            "Mission Control confirms that liftoff is now possible.",
            "Only one final system stands between the mission and the stars.",
            "Deep in the station, the Final Control Room is already waking and waiting for the last logic chain to be solved.",
          ]),
        },
        {
          section: "Logic",
          number: 8,
          title: "Final Logic System",
          rocketPart: "Launch Glow",
          introduction: storyText([
            "Captain Nova enters the Final Control Room, where the last challenge protects the launch sequence itself.",
            "Across the main console stretches a chain of clues, and each one must be understood in the right order before the rocket will accept the command to fly.",
            "This system controls the Launch Glow, the final surge that links every unlocked part into one living machine.",
            "Mission Control can see the skyway to Luma-7 opening beyond the station, bright, narrow, and already beginning to fade at the edges.",
            "Stay calm, solve the final logic chain, and bring the whole rocket to life before the window closes.",
          ]),
          midMissionUpdate: storyText([
            "Mission Update.",
            "The Final Control Room is running out of time.",
            "Lights are blinking on and off across the console, the launch sequence keeps pausing in mid-countdown, and the skyway to Luma-7 is narrowing with every passing second.",
            "If the last clues are not solved now, the rocket could power down with every part assembled but no way to fly.",
            "Captain Nova is strapped in and waiting for the signal, while Mission Control watches the window fade against the stars.",
            "This is the final test, Explorer - hold the logic chain together and awaken the launch.",
          ]),
          rewardDebrief: storyText([
            "Mission complete.",
            "The final clue locks into place, and the entire control system surges awake in a single blaze of light.",
            "A brilliant Launch Glow races across the rocket from base to nose, stitching every unlocked part into one shining machine ready for flight.",
            "The engine hum deepens, the cockpit steadies, and Captain Nova wraps both hands around the controls as the route to Luma-7 burns clear beyond the stars.",
            "Mission Control confirms that all systems are green.",
            "The ship is ready, the countdown is alive, and the great journey can finally begin.",
          ]),
        },
      ],
      endings: [
        {
          id: "ending_95_plus",
          label: "Excellent",
          minScore: 95,
          maxScore: 100,
          text: storyText([
            "With every chamber solved, Captain Nova seals the hatch, settles into the Astronaut Seat, and begins the final countdown.",
            "The Rocket Base grips the launch pad, the Window shines with the path you uncovered, the Wings lock into perfect position, the Engine roars awake, the Launch Flames surge beneath the platform, and the Launch Glow washes the hull in bright silver light.",
            "At zero, the rocket launches.",
            "It blasts upward through clouds of steam and roaring fire, shaking the station as it tears into the night sky.",
            "Earth falls away.",
            "The Moon flashes past.",
            "Stars open in every direction.",
            "Captain Nova follows the route you restored, flying through a river of tumbling debris, banking between spinning rocks and broken ice, then bursting through a glowing comet gate that lights the whole ship blue-white.",
            "Every part works beautifully.",
            "Every system responds instantly.",
            "The rocket flies like it was always meant to reach the impossible.",
            "And then, through the silver storm ahead, Luma-7 appears.",
            "It is more incredible than anyone imagined: blue oceans glowing beneath crystal clouds, giant glassy storm rings circling the planet, green auroras pouring through the sky, and valleys sparkling like they are filled with stars.",
            "Captain Nova guides the ship through the shining atmosphere, dodges a crown of silver lightning, and lands in a wide glowing plain at the foot of a crystal mountain range.",
            "Mission Control erupts in cheers loud enough to rattle the speakers.",
            "Captain Nova sends the first clear hello from Luma-7 back to Earth, followed by images of its skies, its rings, and its mysterious glowing land.",
            "Because of your brilliant work, the beacon was answered.",
            "The hidden planet was reached.",
            "Captain Nova becomes the first explorer to stand on Luma-7, and this mission is remembered forever as one of the greatest adventures in space history.",
          ]),
        },
        {
          id: "ending_85_94",
          label: "Great Job",
          minScore: 85,
          maxScore: 94,
          text: storyText([
            "The countdown reaches zero, and Captain Nova launches into the night with a rocket that feels strong, fast, and almost perfect.",
            "The ship rises in a roar of light, breaks through the clouds, and races away from Earth toward the narrow skyway leading to Luma-7.",
            "The Window glows with the route you helped uncover.",
            "The Engine hums with steady power.",
            "The Wings guide the ship through drifting debris and shimmering comet dust as Captain Nova flies deeper into space.",
            "The beacon ahead grows brighter and brighter until, at last, the hidden planet comes into view.",
            "Luma-7.",
            "A shimmering world wrapped in silver weather, swirling rings, and glowing rivers of light.",
            "Captain Nova reaches orbit and circles the planet, sending back breathtaking images of shining seas, bright storm crowns, enormous mountain shadows, and flashes of green aurora racing across the sky.",
            "Mission Control can barely believe what it is seeing.",
            "But a few systems are not tuned quite well enough for a safe landing.",
            "The ship can orbit.",
            "It can scan.",
            "It can get close.",
            "But the descent would be too risky.",
            "So Mission Control gives the order to turn back.",
            "Even so, the mission is a triumph.",
            "The beacon was reached.",
            "The hidden planet was revealed.",
            "Captain Nova returns to Earth carrying maps, data, and images that will guide the next launch even farther into the unknown.",
            "The first landing will have to wait - but because of you, the path is open.",
          ]),
        },
        {
          id: "ending_75_84",
          label: "Nice Work",
          minScore: 75,
          maxScore: 84,
          text: storyText([
            "Captain Nova launches with courage and a rocket that climbs cleanly into the dark, carrying the dream of Luma-7 high above Earth.",
            "The ship clears the atmosphere, speeds past the Moon, and follows the route you rebuilt through drifting fields of ice, dust, and silent starlight.",
            "For a while, everything feels possible.",
            "The beacon ahead grows stronger.",
            "The Window stays bright.",
            "Captain Nova even catches a first real glimpse of Luma-7 at the far edge of space - glowing through silver storms like a lantern hidden behind clouds.",
            "Mission Control receives distant scans and blurry but thrilling images of the planet's ringed skies.",
            "But as the journey continues, a few systems begin to strain.",
            "Power wobbles.",
            "Guidance needs extra correction.",
            "The ship can still fly, but not with the steady strength needed to cross the final distance safely and begin an approach.",
            "Mission Control makes the hard call to turn back before the mission slips into danger.",
            "Captain Nova returns to Earth with real spaceflight experience, a clearer map, fresh readings of the beacon, and the unforgettable thrill of having seen the hidden world with their own eyes.",
            "The mission falls short of orbit or landing, but it proves something important:",
            "Luma-7 is real.",
            "The route works.",
            "And the next rocket could go all the way.",
          ]),
        },
        {
          id: "ending_60_74",
          label: "Good Effort",
          minScore: 60,
          maxScore: 74,
          text: storyText([
            "The rocket launches with a fierce shake, and Captain Nova guides it upward as alarms flicker and the station falls away below.",
            "The ship breaks through the clouds and reaches space, where Earth glows blue beneath the Window and the stars stretch wide in every direction.",
            "Far ahead in the darkness, the beacon of Luma-7 glimmers like a promise.",
            "For one shining stretch of the journey, it feels like the mission might make it.",
            "The ship follows the early part of the route, crosses into near-Earth space, and captures valuable readings from the skyway.",
            "Captain Nova keeps the rocket steady with skill and focus while Mission Control tracks the flickering signal ahead.",
            "But the voyage cannot hold together for long.",
            "Some systems struggle to work together.",
            "Power rises and falls unevenly.",
            "Guidance needs more correction than the rocket can handle.",
            "The ship does not have the strength or stability it needs to chase Luma-7 safely across deep space.",
            "Mission Control orders an early return before the journey becomes too dangerous.",
            "Captain Nova brings the ship home with calm hands and strong flying, and the mission still earns an important victory: the rocket flew, the beacon was seen, data was collected, and the path ahead became clearer than ever before.",
            "This was not the great crossing to Luma-7 - not yet - but it was a brave step toward it, and the next build will be better prepared.",
          ]),
        },
        {
          id: "ending_below_60",
          label: "Keep Trying",
          minScore: 0,
          maxScore: 59,
          text: storyText([
            "Captain Nova begins the countdown, and for one breathless moment the whole station seems to hold still.",
            "The Engine surges.",
            "The Launch Flames burst unevenly beneath the rocket.",
            "The glowing route to Luma-7 shines across the Window like a dream almost close enough to touch.",
            "Slowly, the ship rises from the pad in a roar of heat and light.",
            "But the rocket is not ready.",
            "Warning lights flood the cockpit.",
            "Key systems pull against one another.",
            "The climb becomes shaky, then unstable.",
            "Captain Nova fights to steady the controls as Mission Control watches the numbers swing in the wrong direction.",
            "The rocket rises only a short distance before the order comes: abort and return.",
            "With calm focus and careful skill, Captain Nova guides the ship safely back to the launch pad while the last of the skyway fades above the station.",
            "The beacon still flashes somewhere far beyond the darkness, unanswered for now.",
            "No one reaches Luma-7 today.",
            "But the mission is not wasted.",
            "Every chamber you cleared revealed more of what the rocket needs.",
            "Every answer brought Captain Nova one step closer to the stars.",
            "Every attempt helped build the path forward.",
            "The hidden planet is still waiting out there beyond the storm rings and the dark, and with stronger problem-solving on the next run, this unfinished launch could one day become a triumphant journey all the way to Luma-7.",
          ]),
        },
      ],
    },
  });

  // Change this id to swap to another storyline pack without touching app logic.
  const activeStorylineId = "cinematicCaptainNova";
  const activeStoryline = storylines[activeStorylineId] || Object.values(storylines)[0];

  const content = {
    hero: {
      eyebrow: "Mission Control",
      title: "Captain Nova's Rocket Mission",
      copy: "A story-driven gifted practice adventure for brave young engineers.",
      metrics: {
        steps: "{count} Mission Steps",
        parts: "{count} Rocket Parts",
        time: "Final Launch in {minutes} Minutes",
      },
    },
    scoreboard: {
      kicker: "Explorer Record",
      awaitingName: "Type an explorer name",
      awaitingScore: "Enter the explorer name below to show only that explorer's best score.",
      loading: "Checking this explorer's saved record.",
      empty: "No saved record yet for this explorer.",
      localSaveSuccess: "Explorer record saved on this device.",
      deviceOnlyWarning: "Explorer record saved on this device. Online sync could not update just now.",
      deviceResetSuccess: "Every saved explorer record on this device has been cleared.",
      allResetSuccess: "Every saved explorer record has been cleared.",
      resetPrompt: "Enter the admin PIN to clear saved explorer records.",
      resetConfirm: "Clear every saved explorer record on this device? This cannot be undone.",
    },
    parentArea: {
      toggle: "Parent Area",
      kicker: "Parent Area",
      copy: "Restart the mission or manage saved scores without interrupting the story.",
      storyOnlyLabel: "Story Only",
      storyOnlyHelp: "Skip the questions and play only the mission story scenes.",
      restart: "Restart Mission",
      reset: "Reset Saved Scores",
    },
    dashboard: {
      buildTitle: "Rocket Build",
      timerLabel: "Mission Timer",
      scoreLabel: "Mission Score",
      buildNote: "Each solved mission step helps Captain Nova finish the rocket.",
      missionsTitle: "Rocket Missions",
      tipTitle: "Captain Nova Tip",
      tipCopy:
        "Take a slow breath, read carefully, and imagine each smart answer clicking a new rocket part into place.",
    },
    start: {
      briefingTitle: "Mission Briefing",
      nameLabel: "Explorer Name",
      namePlaceholder: "Type your explorer name here",
      emptyNameHint: "Mission Control needs your name before the countdown can begin.",
      readyNameHint: "Press Enter to start Mission 1: Verbal Challenge.",
      readyStoryOnlyNameHint: "Press Enter to begin Story Only mode.",
      emptyPrompt: "Type your name to join Captain Nova's mission.",
      readyPrompt: "Hi {name}! Captain Nova is ready for liftoff.",
      counter: "{count} mission steps across {missions} missions",
      badge: "Mission Briefing",
      emptyNextHint: "Type your name to begin the mission.",
      readyNextHint: "Press Enter to start Mission 1: Verbal Challenge.",
      readyStoryOnlyNextHint: "Press Enter to play the story route.",
      playerReadyNote: "Explorer {name}, your mission console is ready.",
    },
    question: {
      counter: "Mission Step {current} of {total}",
      selectHint: "Choose an answer to power up Check Answer.",
      validateHint: "Press Check Answer to power the next rocket step.",
      allAnsweredHint: "All {count} mission steps are complete. Launch the rocket when you are ready.",
      autoAdvanceHint: "Rocket step locked in. Loading the next mission step...",
      lockedHint: "Rocket step locked in. Press Next Mission Step.",
      nextMissionHint: "Rocket part secured. Press Next mission.",
      storyOnlyPrompt: "Story Only mode is on. Follow Captain Nova through each mission scene.",
      storyOnlyHint: "Use the modal button to continue the story.",
      playerNote: "Explorer {name} is flying Mission {missionNumber}.",
      buttons: {
        check: "Check Answer",
        next: "Next Mission Step",
        nextMission: "Next mission",
        launch: "Launch the Rocket",
        finished: "Mission Complete",
        storyOnly: "Story Only Active",
      },
      feedback: {
        correctTitle: "Rocket power confirmed",
        wrongTitle: "Mission Control correction",
        yourAnswer: "Your answer:",
        correctAnswer: "Correct answer:",
        why: "Why:",
        noAnswer: "No answer selected",
      },
    },
    results: {
      eyebrow: "Launch Report",
      summarySuffix: "Captain Nova's launch report is ready below.",
      timeSummary: "Mission time used: {used} of {total}.",
      storyOnlyHeadline: "{name} completed Captain Nova's full story route.",
      storyOnlySummary: "Story Only mode played every mission scene without quiz questions.",
      storyOnlyTimeSummary: "Story Only mode keeps the focus on the adventure, so mission timing is turned off.",
      retry: "Build Another Rocket",
      back: "Return to Mission",
      debriefTitle: "Mission Debrief",
      debriefCopy: "Open this report to review missed mission steps and the correct solutions.",
      perfectTitle: "Legendary Launch",
      perfectBody: "Captain Nova's rocket launched with every system working perfectly.",
      sectionSummary: "{correct} mission steps powered out of {total}",
      sectionPercent: "{percent}% mission power in this system",
      summaryBands: [
        {
          min: 85,
          text: "Legendary engineering. Captain Nova built a rocket ready for deep space.",
        },
        {
          min: 70,
          text: "Strong mission work. A little more precision will send the next rocket even farther.",
        },
        {
          min: 55,
          text: "Good progress. A few more practice missions will make the rocket stronger and steadier.",
        },
        {
          min: 0,
          text: "This launch was a brave start. Review the mission debrief and build an even better rocket next time.",
        },
      ],
      endingTitle: "Captain Nova's Final Flight",
      scorePill: "{percent}% mission score",
      completePill: "Mission Complete",
    },
    activeStorylineId,
    storylines,
    story: activeStoryline,
    gamification: {
      messages: {
        correct: [
          "Rocket power rising!",
          "Mission Control says yes!",
          "Nice work, explorer!",
          "Captain Nova is impressed!",
        ],
        gentle: [
          "Almost there, explorer!",
          "Mission Control has a hint for you.",
          "Keep building, you are doing great!",
          "The next rocket step is waiting!",
        ],
        midpoint: [
          "Star boost unlocked!",
          "Halfway through this mission!",
          "Captain Nova found extra power!",
          "Your rocket just got brighter!",
        ],
        sectionComplete: [
          "Rocket part unlocked!",
          "Mission complete!",
          "Another rocket piece clicked into place!",
          "Captain Nova is ready for the next system!",
        ],
        final: [
          "Countdown complete!",
          "The rocket is ready to launch!",
          "Captain Nova can blast off now!",
          "Adventure complete!",
        ],
      },
      introductionTitle: "Mission Introduction",
      introductionBody: "Captain Nova has a new mission briefing for you.",
      introductionReward: "Unlock: {reward}",
      introductionButton: "Start mission",
      midpointTitle: "Mission Update",
      midpointBody: "The mission is halfway complete, and Captain Nova needs one more strong push.",
      midpointButton: "Continue mission",
      sectionCompleteTitle: "{reward} unlocked!",
      sectionCompleteBody: "Mission complete. Captain Nova just locked {reward} into place.",
      sectionCompleteButton: "Next mission",
      finalTitle: "All missions complete!",
      finalBody: "Every rocket system is in place. Captain Nova can begin the final countdown.",
      finalReward: "Rocket fully assembled",
      finalButton: "Finish mission",
    },
  };

  window.CaptainNovaContent = Object.freeze(content);
})();
