(function () {
  const content = {
    hero: {
      eyebrow: "Mission Control",
      title: "Captain Nova's Rocket Mission",
      copy: "A story-driven gifted practice adventure for brave young engineers.",
      metrics: {
        steps: "{count} Mission Steps",
        parts: "{count} Rocket Parts",
        time: "Final Launch in {minutes} Minutes",
      },
    },
    scoreboard: {
      kicker: "Explorer Record",
      awaitingName: "Type an explorer name",
      awaitingScore: "Enter the explorer name below to show only that explorer's best score.",
      loading: "Checking this explorer's saved record.",
      empty: "No saved record yet for this explorer.",
      localSaveSuccess: "Explorer record saved on this device.",
      deviceOnlyWarning: "Explorer record saved on this device. Online sync could not update just now.",
      deviceResetSuccess: "Every saved explorer record on this device has been cleared.",
      allResetSuccess: "Every saved explorer record has been cleared.",
      resetPrompt: "Enter the admin PIN to clear saved explorer records.",
      resetConfirm: "Clear every saved explorer record on this device? This cannot be undone.",
    },
    parentArea: {
      toggle: "Parent Area",
      kicker: "Parent Area",
      copy: "Restart the mission or manage saved scores without interrupting the story.",
      restart: "Restart Mission",
      reset: "Reset Saved Scores",
    },
    dashboard: {
      buildTitle: "Rocket Build",
      timerLabel: "Mission Timer",
      scoreLabel: "Mission Score",
      buildNote: "Each solved mission step helps Captain Nova finish the rocket.",
      missionsTitle: "Rocket Missions",
      tipTitle: "Captain Nova Tip",
      tipCopy:
        "Take a slow breath, read carefully, and imagine each smart answer clicking a new rocket part into place.",
    },
    start: {
      briefingTitle: "Mission Briefing",
      nameLabel: "Explorer Name",
      namePlaceholder: "Type your explorer name here",
      emptyNameHint: "Mission Control needs your name before the countdown can begin.",
      readyNameHint: "Press Enter to start Mission 1: Verbal Challenge.",
      emptyPrompt: "Type your name to join Captain Nova's mission.",
      readyPrompt: "Hi {name}! Captain Nova is ready for liftoff.",
      counter: "{count} mission steps across {missions} missions",
      badge: "Mission Briefing",
      emptyNextHint: "Type your name to begin the mission.",
      readyNextHint: "Press Enter to start Mission 1: Verbal Challenge.",
      playerReadyNote: "Explorer {name}, your mission console is ready.",
    },
    question: {
      counter: "Mission Step {current} of {total}",
      selectHint: "Choose an answer to power up Check Answer.",
      validateHint: "Press Check Answer to power the next rocket step.",
      allAnsweredHint: "All {count} mission steps are complete. Launch the rocket when you are ready.",
      lockedHint: "Rocket step locked in. Press Next Mission Step.",
      playerNote: "Explorer {name} is flying Mission {missionNumber}.",
      buttons: {
        check: "Check Answer",
        next: "Next Mission Step",
        launch: "Launch the Rocket",
        finished: "Mission Complete",
      },
      feedback: {
        correctTitle: "Rocket power confirmed",
        wrongTitle: "Mission Control correction",
        yourAnswer: "Your answer:",
        correctAnswer: "Correct answer:",
        why: "Why:",
        noAnswer: "No answer selected",
      },
    },
    results: {
      eyebrow: "Launch Report",
      summarySuffix: "Captain Nova's launch report is ready below.",
      timeSummary: "Mission time used: {used} of {total}.",
      retry: "Build Another Rocket",
      back: "Return to Mission",
      debriefTitle: "Mission Debrief",
      debriefCopy: "Open this report to review missed mission steps and the correct solutions.",
      perfectTitle: "Legendary Launch",
      perfectBody: "Captain Nova's rocket launched with every system working perfectly.",
      sectionSummary: "{correct} mission steps powered out of {total}",
      sectionPercent: "{percent}% mission power in this system",
      summaryBands: [
        {
          min: 85,
          text: "Legendary engineering. Captain Nova built a rocket ready for deep space.",
        },
        {
          min: 70,
          text: "Strong mission work. A little more precision will send the next rocket even farther.",
        },
        {
          min: 55,
          text: "Good progress. A few more practice missions will make the rocket stronger and steadier.",
        },
        {
          min: 0,
          text: "This launch was a brave start. Review the mission debrief and build an even better rocket next time.",
        },
      ],
      endingTitle: "Captain Nova's Final Flight",
      scorePill: "{percent}% mission score",
      completePill: "Mission Complete",
    },
    story: {
      title: "Captain Nova's Rocket Mission",
      introduction: {
        kicker: "Introduction",
        pill: "8 Missions to Build the Rocket",
        secondaryPill: "Captain Nova Needs You",
        text: [
          "Welcome, Explorer! Mission Control has an important assignment for you.",
          "Captain Nova is preparing a rocket to explore a mysterious new planet far beyond Earth.",
          "But the rocket is not built yet, and only a brilliant young engineer can assemble it.",
          "Eight missions stand between you and liftoff.",
          "Each mission unlocks a new part of the rocket.",
          "Complete them all, and we launch for the stars!",
        ],
      },
      missions: [
        {
          section: "Verbal",
          number: 1,
          title: "Verbal Challenge",
          rocketPart: "Rocket Base",
          summary: "Glowing words guard the rocket base. Pick the right ones to start the build.",
          text: [
            "Captain Nova enters the first chamber of the space station.",
            "Glowing words float in the air, hiding the foundation of the rocket.",
            "Choose the right words to unlock the rocket base and start building the ship.",
          ],
        },
        {
          section: "Math",
          number: 2,
          title: "Math Challenge",
          rocketPart: "Rocket Body",
          summary: "Solve the number puzzle to snap the rocket body onto the base.",
          text: [
            "With the base secured, Captain Nova moves into the Number Chamber.",
            "Floating numbers spin slowly around the room.",
            "Solve the math puzzle to reveal the rocket body and connect it to the base.",
          ],
        },
        {
          section: "Nonverbal",
          number: 3,
          title: "Pattern Vision",
          rocketPart: "Rocket Window",
          summary: "Find the hidden pattern to unlock the bright window for star watching.",
          text: [
            "In the next room, there are no words and no numbers.",
            "Only shapes and pictures form a mysterious pattern on the walls.",
            "Find the pattern to unlock the bright window that will let Captain Nova see the stars.",
          ],
        },
        {
          section: "Spatial",
          number: 4,
          title: "Spatial Assembly",
          rocketPart: "Rocket Wings",
          summary: "Fit the floating parts together and unfold the rocket wings.",
          text: [
            "The rocket now needs wings to travel safely through the sky.",
            "Pieces of metal float around like a puzzle waiting to be assembled.",
            "Fit them together correctly and the rocket wings unfold into place.",
          ],
        },
        {
          section: "Patterns",
          number: 5,
          title: "Pattern Reactor",
          rocketPart: "Rocket Engine",
          summary: "Complete the glowing pattern to wake up the rocket engine.",
          text: [
            "Deep inside the station, glowing symbols pulse with energy.",
            "They form a repeating pattern that controls the rocket engine.",
            "Find the missing symbol and the powerful engine will activate.",
          ],
        },
        {
          section: "Analogies",
          number: 6,
          title: "Analogy Link",
          rocketPart: "Astronaut Seat",
          summary: "Solve the connection between ideas to unlock Captain Nova's seat.",
          text: [
            "Captain Nova reaches the control room.",
            "Two ideas appear on the main screen, connected in a special way.",
            "Solve the analogy to unlock the astronaut seat inside the rocket.",
          ],
        },
        {
          section: "Categories",
          number: 7,
          title: "Sorting Protocol",
          rocketPart: "Launch Flames",
          summary: "Sort the objects correctly and ignite the launch flames.",
          text: [
            "The rocket is nearly ready.",
            "Different objects float through the air, but only some belong together.",
            "Sort them correctly and bright launch flames ignite beneath the rocket.",
          ],
        },
        {
          section: "Logic",
          number: 8,
          title: "Final Logic System",
          rocketPart: "Launch Glow",
          summary: "Solve the final clues so the launch system glows and the rocket is ready.",
          text: [
            "Only one system remains before liftoff.",
            "A series of clues guards the final launch control.",
            "Solve the logic puzzle and the rocket begins to glow, fully ready for launch.",
          ],
        },
      ],
      endings: [
        {
          id: "ending_95_plus",
          label: "Legendary Launch",
          minScore: 95,
          maxScore: 100,
          text: [
            "Captain Nova climbs into the astronaut seat and begins the countdown.",
            "Every rocket system works perfectly.",
            "The engines ignite with a thunderous roar and the rocket blasts into space.",
            "It races past the Moon and flies toward worlds no explorer has ever seen.",
            "Bright comets, strange planets, and sparkling galaxies appear outside the window.",
            "Thanks to your incredible work, this mission becomes a legendary space adventure.",
          ],
        },
        {
          id: "ending_85_94",
          label: "Strong Mission",
          minScore: 85,
          maxScore: 94,
          text: [
            "The engines roar and the rocket launches smoothly into the sky.",
            "Captain Nova reaches space and begins exploring among the stars.",
            "Most rocket systems work well, though a few parts are not perfectly tuned.",
            "Because of this, the rocket cannot travel quite as far as planned.",
            "Even so, the mission is exciting and successful.",
            "With just a little more precision, the next rocket could reach even deeper space.",
          ],
        },
        {
          id: "ending_75_84",
          label: "Early Return",
          minScore: 75,
          maxScore: 84,
          text: [
            "The rocket lifts off and climbs high above Earth.",
            "Captain Nova reaches space and sees distant planets glowing in the darkness.",
            "However, some rocket parts are not working at full power.",
            "The engines cannot push the ship deeper into the solar system.",
            "Mission Control asks Captain Nova to return earlier than planned.",
            "With better answers during the missions, the next rocket could travel much farther.",
          ],
        },
        {
          id: "ending_60_74",
          label: "Edge of Space",
          minScore: 60,
          maxScore: 74,
          text: [
            "The rocket shakes as it launches, but Captain Nova manages to guide it upward.",
            "Soon the rocket reaches the edge of space and Earth shines below like a blue marble.",
            "Several systems struggle to keep the rocket flying smoothly.",
            "The engines cannot maintain full power for long.",
            "Mission Control orders an early return to keep everyone safe.",
            "Stronger solutions in the missions would have built a much better rocket.",
          ],
        },
        {
          id: "ending_below_60",
          label: "Launch Attempt",
          minScore: 0,
          maxScore: 59,
          text: [
            "Captain Nova starts the engines, but something is clearly wrong.",
            "The rocket rises only a short distance before warning lights begin flashing.",
            "Several important rocket parts were not built correctly.",
            "Captain Nova carefully brings the rocket back to the launch pad.",
            "This mission cannot reach space today.",
            "But with better problem solving, the next rocket could be powerful enough to reach the stars.",
          ],
        },
      ],
    },
    gamification: {
      messages: {
        correct: [
          "Rocket power rising!",
          "Mission Control says yes!",
          "Nice work, explorer!",
          "Captain Nova is impressed!",
        ],
        gentle: [
          "Almost there, explorer!",
          "Mission Control has a hint for you.",
          "Keep building, you are doing great!",
          "The next rocket step is waiting!",
        ],
        midpoint: [
          "Star boost unlocked!",
          "Halfway through this mission!",
          "Captain Nova found extra power!",
          "Your rocket just got brighter!",
        ],
        sectionComplete: [
          "Rocket part unlocked!",
          "Mission complete!",
          "Another rocket piece clicked into place!",
          "Captain Nova is ready for the next system!",
        ],
        final: [
          "Countdown complete!",
          "The rocket is ready to launch!",
          "Captain Nova can blast off now!",
          "Adventure complete!",
        ],
      },
      midpointBody: "You reached the halfway point and Mission Control unlocked a star boost.",
      sectionCompleteBody: "Mission complete. Captain Nova just locked {reward} into place.",
      finalBody: "All 8 rocket parts are ready. Captain Nova can launch into the stars now.",
    },
  };

  window.CaptainNovaContent = Object.freeze(content);
})();
